#!/usr/bin/perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
#
# Licensed under the terms of the GNU GPL v3, or any later version.

use strict;
use warnings;
use utf8;

my $acpi;
my $status;
my $percent;
my $full_text;
my $short_text;
my $text_colour;
my $bat_number = $ENV{BLOCK_INSTANCE} || 0;

# read the first line of the "acpi" command output
open (ACPI, "acpi -b | grep 'Battery $bat_number' |") or die;
$acpi = <ACPI>;
close(ACPI);

# fail on unexpected output
if ($acpi !~ /: (\w+), (\d+)%/) {
    die "$acpi\n";
}

$status = $1;
$percent = $2;
$full_text = "$percent%";

if ($status eq 'Discharging') {
    $full_text .= ' DIS';

    if ($percent < 20) {
        $text_colour="#FF0000\n";
    } elsif ($percent < 40) {
        $text_colour="#FFAE00\n";
    } elsif ($percent < 60) {
        $text_colour="#FFF600\n";
    } elsif ($percent < 85) {
        $text_colour="#A8FF00\n";
    }
} elsif ($status eq 'Charging') {
    $full_text .= ' CHR';
}

$short_text = $full_text;

if ($acpi =~ /(\d\d:\d\d):/) {
    $full_text .= " ($1)";
}

print "$full_text\n";
print "$short_text\n";

if ($text_colour ne "") {
    print $text_colour;

    if ($percent < 5) {
        exit(33);
    }
}

exit(0);
