#!/bin/sh
#
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
#
# Licensed under the terms of the GNU GPL v3, or any later version.

DIR="${BLOCK_INSTANCE:-$HOME}"
ALERT_LOW="${1:-10}" # color will turn red under this value (default: 10%)

df -h -P -l "$DIR" | awk -v alert_low=$ALERT_LOW '
/\/.*/ {
    # full text
    print $4

    # short text
    print $4

    use=$5

    # no need to continue parsing
    exit 0
}

END {
    gsub(/%$/,"",use)
    if (100 - use < alert_low) {
        # color
        print "#FF0000"
    }
}
'
