#!/bin/sh
#
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
#
# Licensed under the terms of the GNU GPL v3, or any later version.

DIR="${DIR:-$BLOCK_INSTANCE}"
DIR="${DIR:-$HOME}"
ALERT_LOW="${ALERT_LOW:-$1}"
ALERT_LOW="${ALERT_LOW:-10}" # color will turn red under this value (default: 10%)

if [ ! -d "${DIR}" ]; then
    echo; exit 0
fi

LOCAL_FLAG="-l"
if [ "$1" = "-n" ] || [ "$2" = "-n" ]; then
    LOCAL_FLAG=""
fi

df -h -P "$LOCAL_FLAG" "$DIR" | awk -v label="$LABEL" -v alert_low="$ALERT_LOW" '
/\/.*/ {
    # full text
    print label $4

    # short text
    print label $4

    use=$5

    # no need to continue parsing
    exit 0
}

END {
    gsub(/%$/,"",use)
    if (100 - use < alert_low) {
        # color
        print "#FF0000"
    }
}
'
