#!/bin/bash

# NOTE!
# This script has been modified to work with HDMI.
# Previously, -c0 was defined in all amixer commands
# to specify the card to be used. That was removed so
# that instead, amixer would simply use the default card.
#
# If for some reason it no longer works on normal speakers, revert.

# The instance option sets the control to report and configure
CHANNEL="${BLOCK_INSTANCE:-Master}"
LABEL="${LABEL:-}"

# The first parameter sets the step to change the volume by
STEP="${1:-5%}"

case $BLOCK_BUTTON in
    1) pavucontrol --class=pavu_floating & sleep 0.2 && i3-msg '[class="pavu_floating"] floating enable, resize set 450px 500px, move position mouse, move down 25px' & ;; # left click, launch mixer
    3) amixer -q -cS5 sset "$CHANNEL" toggle && pkill -RTMIN+10 i3blocks ;; # right click, mute/unmute
    4) amixer -q -cS5 sset "$CHANNEL" "${STEP}"+ unmute ;; # scroll up, increase
    5) amixer -q -cS5 sset "$CHANNEL" "${STEP}"- unmute ;; # scroll down, decrease
esac

perl_filter='if (/.*\[(\d+%)\] (\[(-?\d+.\d+dB)\] )?'
perl_filter+='\[(on|off)\]'
# shellcheck disable=2016
perl_filter+='/){CORE::say $4 eq "off" ? "MUTE" : "$1"; exit}'

echo -n "${LABEL}"
amixer get -cS5 "$CHANNEL" | perl -ne "$perl_filter"
