#!/bin/sh
#
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
#
# Licensed under the terms of the GNU GPL v3, or any later version.

TYPE="${BLOCK_INSTANCE:-mem}"

awk -v type=$TYPE '
/^MemTotal:/ {
    mem_total=$2
}
/^MemFree:/ {
    mem_free=$2
}
/^Buffers:/ {
    mem_free+=$2
}
/^Cached:/ {
    mem_free+=$2
}
/^SwapTotal:/ {
    swap_total=$2
}
/^SwapFree:/ {
    swap_free=$2
}
END {
    # full text
    if (type == "swap")
        printf("%.1fG\n", (swap_total-swap_free)/1024/1024)
    else
        printf("%.1fG\n", mem_free/1024/1024)

    # TODO: short text

    # TODO: color (if less than X%)
}
' /proc/meminfo
