#!/bin/sh
#
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
#
# Licensed under the terms of the GNU GPL v3, or any later version.

TYPE="${BLOCK_INSTANCE:-mem}"

awk -v type="$TYPE" '
/^MemTotal:/ {
    mem_total=$2
}
/^MemFree:/ {
    mem_free=$2
}
/^Buffers:/ {
    mem_free+=$2
}
/^Cached:/ {
    mem_free+=$2
}
/^SwapTotal:/ {
    swap_total=$2
}
/^SwapFree:/ {
    swap_free=$2
}
END {
    if (type == "swap") {
        free=swap_free/1024/1024
        used=(swap_total-swap_free)/1024/1024
        total=swap_total/1024/1024
    } else {
        free=mem_free/1024/1024
        used=(mem_total-mem_free)/1024/1024
        total=mem_total/1024/1024
    }

    pct=0
    if (total > 0) {
        pct=100-(used/total*100)
    }

    # full text
    printf("%.1fG (%.f%%)\n", free, pct)

    # short text
    printf("%.1fG\n", free)

    # color
    if (pct < 10) {
        print("#FF0000")
    } else if (pct < 20) {
        print("#FFAE00")
    } else if (pct < 30) {
        print("#FFF600")
    }
}
' /proc/meminfo
