#!/bin/bash

# Requires sudoers set to NOPASSWD
# Comment out if you'd rather run manually
#
# We use this instead of checkupdates so that
# our `aurupdates` command is kept up to date
sudo pacman -Sy > /dev/null
updates=$(pacman -Sup | wc -l)

updates=$(checkupdates | wc -l)

if (( updates == 0 )); then
    echo ""
    exit
fi

if (( updates < 10 )); then
    fgcolor="#FFFFFF"
elif (( updates <= 25 )); then
    fgcolor="#CCFF00"
elif (( updates <= 50 )); then
    fgcolor="#FFFF00"
elif (( updates <= 75 )); then
    fgcolor="#FFAA00"
elif (( updates < 100 )); then
    fgcolor="#FF0000"
else
    fgcolor="#FFFFFF"
fi

fmt="foreground=\"$fgcolor\""
if (( updates >= 100 )); then
    fmt+=' background="#FF2400"'
    updates+=" (!!)"
fi

echo "<span $fmt> $LABEL$updates </span>"
