#!/bin/bash

bgcolor="#000000"

# Requires sudoers set to NOPASSWD
# Comment out if you'd rather run manually
sudo pacman -Sy > /dev/null

updates=$(pacman -Sup | wc -l)

if (( updates == 0 )); then
    echo ""
    exit
else
    text="$updates update"
    (( updates > 1 )) && text+="s"

    if (( updates < 10 )); then
        fgcolor="#CCFF00"
    elif (( updates <= 25 )); then
        fgcolor="#FFFF00"
    elif (( updates <= 50 )); then
        fgcolor="#FFAA00"
    elif (( updates < 100 )); then
        fgcolor="#FF0000"
    else
        fgcolor="#FFFFFF"
        bgcolor="#FF0000"
        text+=" (!!)"
    fi

    text+=" available"
fi

fmt="background=\"$bgcolor\""
fmt+="foreground=\"$fgcolor\""

echo "<span $fmt>$text</span>"
