#!/bin/bash

bgcolor=""

# Requires sudoers set to NOPASSWD
# Comment out if you'd rather run manually
sudo pacman -Sy > /dev/null

updates=$(pacman -Sup | wc -l)

if (( updates == 0 )); then
    echo ""
    exit
else
    text="$updates"

    if (( updates < 10 )); then
        fgcolor="#CCFF00"
    elif (( updates <= 25 )); then
        fgcolor="#FFFF00"
    elif (( updates <= 50 )); then
        fgcolor="#FFAA00"
    elif (( updates < 100 )); then
        fgcolor="#FF0000"
    else
        fgcolor="#FFFFFF"
        bgcolor="#FF2400"
        text+=" (!!)"
    fi
fi

fmt="foreground=\"$fgcolor\""
if [ "$bgcolor" != "" ]; then
    fmt+=" background=\"$bgcolor\""
fi

if [ "$text" != "" ]; then
    echo "<span $fmt> $LABEL$text </span>"
else
    echo ""
fi
