#!/bin/bash

# The instance option sets the control to report and configure
SCONTROL="${BLOCK_INSTANCE:-Master}"

# The first parameter sets the step to change the volume by (and units to display)
STEP="${1:-5%}"

format() {
    perl_filter='if (/.*\[(\d+%)\] (\[(-?\d+.\d+dB)\] )?'
    [ $SCONTROL != "PCM" ] && perl_filter+='\[(on|off)\]'
    perl_filter+='/){CORE::say $4 eq "off" ? "MUTE" : "$1"; exit}'
    perl -ne "$perl_filter"
}

case $BLOCK_BUTTON in
    3) amixer -qc0 -D pulse sset Master toggle && pkill -RTMIN+10 i3blocks ;; # right click, mute/unmute
    4) amixer -qc0 sset $SCONTROL ${STEP}+ unmute ;; # scroll up, increase
    5) amixer -qc0 sset $SCONTROL ${STEP}- unmute ;; # scroll down, decrease
esac

amixer -c0 get $SCONTROL | format
