#!/usr/bin/env bash

pacupdates=$(checkupdates 2>/dev/null | wc -l)
aurupdates=$(pacaur -Qum 2>/dev/null | wc -l)

if (( pacupdates == 0 )) && (( aurupdates == 0 )); then
    echo ""
    exit
fi

if (( updates >= 100 )); then
    updates+=" (!!)"
fi

echo -n "$pacupdates"

if [ "$aurupdates" -gt 0 ]; then
    echo -n "+$aurupdates"
fi

echo
