#!/usr/bin/env bash

# Requires sudoers set to NOPASSWD
# Comment out if you'd rather run manually
sudo pacman -Sy > /dev/null 2>&1

if command -v yay > /dev/null; then
    pacupdates=$(yay -Qun 2>/dev/null | wc -l)
    aurupdates=$(yay -Qum 2>/dev/null | wc -l)
elif command -v pacaur > /dev/null; then
    # Pacaur includes ignored packages so we need to grep them out
    pacupdates=$(pacaur -Qun 2>/dev/null | grep -c -v '[ ignored ]')
    aurupdates=$(pacaur -Qum 2>/dev/null | grep -c -v '[ ignored ]')
else
    # This was previously the only command being run for main repo
    # updates. Hopefully aurupdates should still be in sync thanks
    # to repos being updated on line 5. This breaks when there are
    # broken dependencies, so it should be used as a last resort.
    pacupdates=$(pacman -Sup 2>/dev/null | wc -l)
    aurupdates=0
fi

if (( pacupdates == 0 )) && (( aurupdates == 0 )); then
    echo ""
    exit
fi

fgcolor=""
if (( pacupdates <= 10 )); then
    fgcolor="#ffffff"
elif (( pacupdates <= 25 )); then
    fgcolor="#CCFF00"
elif (( pacupdates <= 50 )); then
    fgcolor="#ffb52a"
elif (( pacupdates <= 75 )); then
    fgcolor="#bd2c40"
elif (( pacupdates < 100 )); then
    fgcolor="#ff0000"
fi

fmt="%{F${fgcolor}}"

if (( pacupdates >= 100 )); then
    pacupdates+=" (!!)"
    fmt+="%{F${fgcolor}}%{B#bd2c40}"
elif (( pacupdates > 10 )); then
    fmt+="%{u${fgcolor}}"
fi

echo -n "${fmt}     ${pacupdates}"

if (( aurupdates > 0 )); then
    echo -n "+$aurupdates"
fi

echo "   %{F-}%{u-}"
