#!/usr/bin/env bash

readonly GH_API="https://api.github.com"

readonly bold=$(tput bold)
readonly reset=$'\e[0m'
readonly red=$'\e[31m'
readonly green=$'\e[32m'
readonly yellow=$'\e[33m'
readonly magenta=$'\e[35m'
readonly cyan=$'\e[36m'
readonly white=$'\e[37m'

main() {
    simplecheck Repo n

    packages="$(simplecheck AUR m)"
    echo "$packages"

    header "AUR (Git) Packages"
    gitcheck | column -t -s'|'
}

simplecheck() {
    header "${1} Packages"
    pacaur -Qu "-${2}"
    echo
}

gitcheck() {
    local package version src branch hash

    mkdir -p ~/.cache/aurcheck-git
    cd ~/.cache/aurcheck-git || return

    while read -r package version; do
        # Skipping already listed updates and non-git packages
        if [[ $packages == *"$package"* ]] || grep -qv '\-git$' <<< "$package"; then
            continue
        fi

        fetch_metadata
        check_sources
        find_latest_commit
        pkg_status
    done <<< "$(pacaur -Qm)"
}

fetch_metadata() {
    curl -so "${package}.PKGBUILD" "https://aur.archlinux.org/cgit/aur.git/plain/.SRCINFO?h=${package}"
}

check_sources() {
    read -r src branch <<< "$(grep -m 1 'source = ' "${package}.PKGBUILD" | parse_ghurl)"

    if [ -z "$branch" ]; then
        query_default_branch
    fi
}

query_default_branch() {
    if [ ! -f "${package}.branch" ]; then
        curl -s "${GH_API}/repos/${src}" | jq -r .default_branch > "${package}.branch"
    fi

    branch=$(<"${package}.branch")
}

find_latest_commit() {
    hash=$(curl -s "${GH_API}/repos/${src}/git/refs/heads/${branch}" | jq -r '.object.sha')
}

pkg_status() {
    echo -en "${bold}${cyan}:: ${magenta}aur-git|${white}${package} "
    echo -en "(${yellow}${src}${white}@${cyan}${branch}${white})|"
    echo -e "${red}${version}${reset}|->|${bold}${green}${hash:0:8}${reset}"
}

header() {
    echo "----------------------------------------"
    echo " $1"
    echo "----------------------------------------"
}

parse_ghurl() {
    sed -e 's/.*github.com\///g' -e 's/\(\.git$\|\(\.git\)\?\#branch=\)/ /g'
}

main

# vi: set ff=sh
