#!/usr/bin/env bash

main() {
    simplecheck Repo n
    simplecheck AUR m
    gitcheck
}

simplecheck() {
    header "${1} Packages"
    pacaur -Qu "-${2}"
    echo
}

gitcheck() {
    local package version

    header "AUR (Git) Packages"
    mkdir -p /tmp/aurcheck-git
    cd /tmp/aurcheck-git

    while read -r package version; do
        if grep -qv '\-git$' <<< "$package"; then
            # Skipping -git package
            continue
        fi

        echo "Checking updates for ${package} (Installed: ${version})"
        fetch_metadata
        echo

    done <<< "$(pacaur -Qm)"
}

fetch_metadata() {
    echo "Fetching package SRCINFO..."
    curl -so "${package}.PKGBUILD" "https://aur.archlinux.org/cgit/aur.git/plain/.SRCINFO?h=${package}"
}

header() {
    echo "----------------------------------------"
    echo " $1"
    echo "----------------------------------------"
}

main

# vi: set ff=sh
