#!/bin/bash

[[ $1 =~ ^(clean(up)?|purge)$ ]] && PURGING="Y"

cd "${DOTFILES_PATH:-$HOME/.files}"/stowable || cd ~/dotfiles/stowable || exit

hash stow 2>/dev/null || case $(grep "^ID=" /etc/os-release | sed 's/ID=//') in
    arch) sudo pacman --noconfirm -S stow ;;
    ubuntu) sudo apt-get install -qy stow ;;
    *) echo "[ERROR] Don't know how to install stow!"; exit 1 ;;
esac

for package in *; do
    lockfile="$package/.stowlock"
    targetfile="$package/.stowtarget"
    target="$( [[ -f "$targetfile" ]] && eval echo "$(<"$targetfile")" || echo "$HOME/.config/$package" )"

    mkdir -p "$target"

    if [[ -n $PURGING ]]; then
        action="Deleting" flag="--delete"
    elif [[ -f "$lockfile" ]]; then
        action="Restowing" flag="--restow"
    else
        action="Stowing" flag="--stow"
    fi

    echo "$action package '$package'" && touch "$lockfile"

    [[ $target == /home/* ]] && cmd="stow" || cmd="sudo stow"

    $cmd --target="$target" --ignore=".stowlock" --ignore=".stowtarget" $flag "$package"

    if [[ "$flag" == "--delete" ]]; then
        rm "$lockfile"
    fi
done && echo "Done!"
