#!/bin/bash

cd ~/.files || cd ~/dotfiles || exit
hash stow 2>/dev/null || exit

case $(grep "^ID=" /etc/os-release | sed 's/ID=//') in
    arch) sudo pacman -S stow ;;
    ubuntu) sudo apt-get install -qy stow ;;
    *) echo "[ERROR] Don't know how to install stow!"; exit 1 ;;
esac

[[ $1 =~ ^(clean(up)?|purge)$ ]] \
    && action="Deleting" flag="--delete" \
    || action="Stowing" flag="--stow"

for package in *; do
    lockfile="$package/.stowlock"
    targetfile="$package/.stowtarget"
    target="$( [[ -f "$targetfile" ]] && eval echo "$(<"$targetfile")" || echo "$HOME/.config/$package" )"

    mkdir -p "$target"

    if [[ -f "$lockfile" ]] && [[ $action == "Stowing" ]]; then
         action="Restowing" flag="--restow"
    fi

    echo "$action package '$package'" && touch "$lockfile"

    [[ $target == /home/* ]] && cmd="stow" || cmd="sudo stow"

    $cmd --target="$target" --ignore=".stowlock" --ignore=".stowtarget" $flag "$package"

    if [[ "$flag" == "--delete" ]]; then
        rm "$lockfile"
    else
        unset action flag
    fi
done && echo "Done!"
