let mapleader=" "

source ~/.config/nvim/plugins.vim
source ~/.vim/settings.vim
source ~/.config/nvim/functions.vim

" Shared configs
source ~/.config/nvim/configs/airline.vim
source ~/.config/nvim/configs/colours.vim
source ~/.config/nvim/configs/gutentags.vim
source ~/.config/nvim/configs/import-cost.vim
source ~/.config/nvim/configs/mundo.vim
source ~/.config/nvim/configs/schlepp.vim
source ~/.config/nvim/configs/startify.vim

" Vim-specific configs
source ~/.config/nvim/configs/ale.vim
source ~/.config/nvim/configs/ctrlp.vim
source ~/.config/nvim/configs/ncm2.vim
source ~/.config/nvim/configs/nerdtree.vim
source ~/.config/nvim/configs/tagbar.vim
