#!/usr/bin/env sh

[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources
[ -f ~/.Xmodmap ] && xmodmap ~/.Xmodmap

if [ -x /usr/bin/gnome-keyring-daemon ]; then
    eval "$(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)"
    export SSH_AUTH_SOCK
else eval "$(ssh-agent)"; fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        # shellcheck source=/etc/X11/xinit/xinitrc.d/50-systemd-user.sh
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

for autostart in udiskie numlockx redshift-gtk; do
    command -v $autostart 2>/dev/null && $autostart &
done

setxkbmap -option compose:menu

nextshot -t &
[ -d ~/nextcloud ] && nextcloud &

exec i3
